### ISSUE TITLE
distance near pole

### ISSUE THREAD

**Issue by fandongwei** [segasai/q3c#12]
I've test two points' distance near pole using sentence
select degrees(q3c_dist(radians(0),radians(90),radians(180),radians(89.9)))
the distance should be 0.1 degree, but it returns "179.932445023645"
even 
select degrees(q3c_dist(radians(0),radians(90),radians(180),radians(90)))
returns "179.932342092551"

**Comment by segasai** [comment]
Hi, 

All the units q3c uses are in degrees. 

> select (q3c_dist((0),(90),(180),(89.9)));
     q3c_dist      
-------------------
 0.100000000000001
(1 row)

So it returns a correct result.
