### ISSUE TITLE
q3c_pixarea minor bug

### ISSUE THREAD

**Issue by gshennessy** [segasai/q3c#14]
The depth claimed to need to be less than 30, but 30 works. Minor fence posting error.

gsh=# select q3c_pixarea(0,31);
ERROR:  Invalid depth. It should be less than 30.
gsh=# select q3c_pixarea(0,30);
   q3c_pixarea    
------------------
 2.09439510239319
(1 row)
gsh=#

**Comment by segasai** [comment]
Thanks! Change committed.
