### ISSUE TITLE
Feature: Cone intersect with quadrilateral

### ISSUE THREAD

**Issue by acscott** [segasai/q3c#15]
Hi!

Any hints on how to do a cone search against rows containing 4 RA & Dec points defining a quadrilateral?

**Comment by segasai** [comment]
On May 10, 2019 08:17, acscott <notifications@github.com> wrote:Hi!
Any hints on how to do a cone search against rows containing 4 RA & Dec points defining a quadrilateral?Hi, If you just want to do 4 cone searches around different rows  in a table you can do q3c_join.Sergey

**Comment by acscott** [comment]
Thank you for getting back so quickly!
More specifically how to test if a cone intersects quadrilateral instead of against a point. (The quadrilateral defined by the 4 points in each row).

**Comment by segasai** [comment]
On Fri, 2019-05-10 at 08:59 -0700, acscott wrote:
> Thank you for getting back so quickly!
> More specifically how to test if a cone intersects quadrilateral instead of against a point. (The quadrilateral defined by the 4 points in each row).

I am not sure there is an easy way to do that in SQL that is exact. 
In the past when I did that, I usually did the cone search with larger aperture and
then double check in python using some geometry package. 

The pgsphere package is one alternative. it has support for geometry operations over various shapes. It may have 
a circle overlaps polygon operator...

**Comment by acscott** [comment]
Thank you!
