### ISSUE TITLE
"make test" should "drop database if exists q3c_test" before "createdb q3c_test"?

### ISSUE THREAD

**Issue by esabol** [segasai/q3c#26]
Minor thing: I just upgraded our installation from q3c 1.5.0 to 2.0.0, and I mistakenly executed `make test` before `make install`. Well, the test failed (because of the proper motion syntax changes in 2.0.0), and it left the `q3c_test` database intact. Subsequent `make test` attempts failed because it doesn't expect the `q3c_test` database to exist.

```
> env PGUSER=postgres make test
createdb q3c_test
createdb: database creation failed: ERROR:  database "q3c_test" already exists
gmake: *** [test] Error 1
```
Also, wow, "make test" takes a lot longer to run now, like 5 x longer than with 1.5.0. Just a lot more testing going on, I guess?

**Comment by segasai** [comment]
Yes, I was considering to do drop database before, but was worried if it could accidentally drop the user's db. But I feel that it is safe enough. so I committed that change. 

And yes, there is significantly more testing now, indeed. The testing time is not really a problem IMO.

**Comment by esabol** [comment]
> And yes, there is significantly more testing now, indeed. The testing time is not really a problem IMO.

I agree that it's not an issue. I just found the increase remarkable. Cheers!

P.S. Don't forget my PR. :)

**Comment by segasai** [comment]
Yes, thanks, I actually didn't see the PR. I have changed the notifications rules for github and stopped seeing even issues/PRs, need to fix that.
