### ISSUE TITLE
Add instructions for upgrading to README.md?

### ISSUE THREAD

**Issue by esabol** [segasai/q3c#27]
May I suggesting adding some instructions to README.md regarding how to upgrade an existing installation? It's really simple, but I think it's worth mentioning.

```SQL
ALTER EXTENSION q3c UPDATE;
```
Or to a specific version:
```SQL
ALTER EXTENSION q3c UPDATE TO '2.0.0';
```
This query is also useful:
```SQL
SELECT * FROM pg_available_extension_versions WHERE name ='q3c';
```

Or maybe there there could be a `make upgrade` target in the Makefile which does `make install` and then does the `ALTER EXTENSION q3c UPDATE;` automatically?

**Comment by segasai** [comment]
Thanks. I've never got very comfortable with extensions and their versions. 
But yes I think the update instruction is useful. 
I wasn't aware myself of the 
```
SELECT * FROM pg_available_extension_versions WHERE name ='q3c';
```
query. I'll try to add something meaningful to the readme... (I'll keep the issue open in the mean time)

**Comment by segasai** [comment]
Fixed. Thanks for the suggestion.
