### ISSUE TITLE
Regression test failure with q3c_ang2ipix test

### ISSUE THREAD

**Issue by segasai** [segasai/q3c#29]
This issue is here to track the problem raised in #28 by @df7cb

**Comment by df7cb** [comment]
I raised a false alarm, I was running the testsuite from git HEAD against the installation from the v2.0.0 tag. Your query from #28 yields a long list of output on v2.0.0, but 0 rows on HEAD.
Sorry for the noise, I was doing too many things in parallel here I think.

**Comment by segasai** [comment]
Okay, that is what I was suspecting.
Thanks anyway!
