### ISSUE TITLE
gcc gen_data.c -lm  -o gen_data -- > fatal error: postgres.h: No such file or directory

### ISSUE THREAD

**Issue by cosmoJFH** [segasai/q3c#8]
The execution of 

$make test 

throws the error fatal error: postgres.h: No such file or directory.

I have checked that the issue can be fixed making the following change in the Make file:

$(CC) $< $(MYBINLIBS)  $(CPPFLAGS) -o $@

I am using 

q3c-1.4.24
ubuntu 14.04
postgresql 9.5.2
and pg_config is defined in the path.

Does this solution has sense for you?

**Comment by segasai** [comment]
Thanks for reporting, the issue was fixed half a year ago in 2d2d5e9 though (I should have made a new release back then...), i'll create one this week then
