### ISSUE TITLE
Execution of make test fails.

### ISSUE THREAD

**Issue by cosmoJFH** [segasai/q3c#9]
The execution of 

$ make test

fails:

gcc gen_data.c -lm  -DQ3C_VERSION='"v1.4.24"'  -O3 -D_GNU_SOURCE -D__STDC_FORMAT_MACROS -I. -I./ -I/usr/include/postgresql/9.5/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -o gen_data
createdb q3c_test
psql q3c_test -c "CREATE TABLE test (ra double precision, dec double precision)"
CREATE TABLE
psql q3c_test -c "CREATE TABLE test1 (ra double precision, dec double precision)"
CREATE TABLE
psql q3c_test -c "CREATE TABLE test_small (ra double precision, dec double precision)"
CREATE TABLE
./gen_data 1 1000000 | psql q3c_test -c "COPY test FROM STDIN WITH DELIMITER ' '"
COPY 1000000
./gen_data 2 1000000 | psql q3c_test -c "COPY test1 FROM STDIN WITH DELIMITER ' '"
COPY 1000000
./gen_data 3 100000 | psql q3c_test -c "COPY test_small FROM STDIN WITH DELIMITER ' '"
COPY 100000
psql q3c_test -c '\i q3c.sql'
BEGIN
SET
psql:q3c.sql:8: ERROR:  could not access file "$libdir/q3c": No such file or directory

This variables is created during the execution of the the command $make

sed 's,MODULE_PATHNAME,$libdir/q3c,g' q3c.sql.in >q3c.sql

But it looks like $libdir is not defined.

I am using

q3c-1.4.24
ubuntu 14.04
postgresql 9.5.2
and pg_config is defined in the path.

**Comment by segasai** [comment]
Thanks for reporting, the issue was fixed half a year ago in 2d2d5e9769c77c4dffb1ec39e1b6ca038bb40dd8 though (I should have made a new release back then...), i'll create one this week then

**Comment by segasai** [comment]
q3c has to be installed first. the error seems to be caused by you not running make install first. at least in my test with PG9.3 and ubuntu 14.04 it works fine after make install, and fails with the error that you see if you don't do make install

**Comment by cosmoJFH** [comment]
Thanks, that fixed the issue.
